Mini1385/login
4sitive/client pull request #27
Opened 2021-06-12 10:26 UTC by mini1385

## 작업 내용 
- login 화면 그리기

resolve: #26

2021-06-13 16:31 UTC, sabgilhun requested changes
확인 부탁드립니다~

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/java/org/positive/daymotion/presentation/base/BaseActivity.kt
> +    protected val binding: B by lazy { DataBindingUtil.setContentView<B>(this, layoutId) }
이거 저번에 버그 찾다가 넣은 변경사항 같은데 없어도 될것 같아요.

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/java/org/positive/daymotion/presentation/login/LoginActivity.kt
> +        window.statusBarColor = ContextCompat.getColor(applicationContext!!, R.color.colorWhite)
이 부분은 테마로 status bar는 투명, 배경은 white로 지정해뒀기 때문에 없어도 될거에요.

```
<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
	<item name="android:statusBarColor">@color/transparent</item>
	<item name="android:windowLightStatusBar">true</item>
	<item name="android:windowBackground">@color/background</item>
         ...
</style>
```

앱 전체에 디자인적인 무언가를 지정하고 싶을때 저기에 추가하면 됩니다.

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/java/org/positive/daymotion/presentation/login/LoginActivity.kt
> +        fun btnSet(btn: Button, str: String, word: String) {
btnSet, tvSet 함수가 onCreate 함수 내부에 있는데 이렇게 사용하신 의도가 특별히 있는게 아니라면 빼는게 좋아보입니다.
함수는 class 내부에 두는게 기본적인 방식이고, 위와 같은 Local function은 인자를 공유가 필요할때 사용하기도 합니다. (잘 안쓰여요)
(https://kotlinlang.org/docs/functions.html#function-scope)

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/java/org/positive/daymotion/presentation/login/LoginActivity.kt
> +        val googleBtn = findViewById<Button>(R.id.googleLoginButton)
```
val googleBtn = binding.googleLoginButton
```
이렇게 쓰시는게 Databinding입니다. 따로 findViewById 하지 않아도 돼요

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/res/layout/activity_login.xml
> +			tools:ignore="MissingConstraints">
이거 없어도 됩니다. (다른 곳에 쓰인 것도 다 지우셔도 될 거예요)

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/res/layout/activity_login.xml
> +				android:lineSpacingExtra="5dp"
제플린에 android:lineSpacingExtra 값 6sp로 되어 있네요.

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/res/layout/activity_login.xml
> +			<Button
이건 제안드리는건데, 버튼을 사용해서 내부를 변경하는 방식을 쓰느라 여러 코드들이 추가되고 있는거 같아서요.

아래와 같이 레이아웃으로 배치를 하면 특정 글자를 찾아서 볼드 처리하는 부분, 아이콘 사이즈 지정하기위해 만든 drawable들을 제거 할 수 있을것 같아요. 

```
<LinearLayout
    android:id="@+id/button"
    android:background="@drawable/background_login_button"
    android:layout_width="match_parent"
    android:layout_height="55dp"
    android:orientation="horizontal">
    
    <TextView
        android:id="@+id/name1"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:layout_marginStart="20dp"
        android:fontFamily="@font/kopub_dotum_bold"
        android:text="Google" />
    
    <TextView
        android:id="@+id/name2"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_gravity="center"
        android:layout_weight="1"
        android:fontFamily="@font/kopub_dotum_light"
        android:text="로 참여하기" />
    
    <ImageView
        android:layout_width="37dp"
        android:layout_height="37dp"
        android:layout_gravity="center_vertical"
        android:layout_marginEnd="16dp"
        android:src="@drawable/ic_login_kakao" />
</LinearLayout>
```

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/res/layout/activity_login.xml
> +				android:drawableRight="@drawable/facebook_icon"
Right보단 Start를 쓰는게 좋습니다. drawableRight -> drawableEnd

하나의 화면에서 [start, end]와 [left, right] 방식의 표기법을 같이 쓰면 문제가 생길 수 있어요

(다른 버튼에도 있으니 같이 수정 부탁드릴게요~)

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/res/layout/activity_login.xml
> +				android:drawablePadding="37dp"
이 패딩 없어도 될겁니다.

(다른 버튼에도 있으니 같이 수정 부탁드릴게요~)

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/res/layout/activity_login.xml
> +				android:layout_toRightOf="@id/infoIcon"
android:layout_toEndOf로 바꿔주세요.

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/res/layout/activity_login.xml
> +			<TextView
자세히 보시면 아이콘과 텍스트가 센터가 맞지 않아요.

RelativeLayout로는 해결 안될 수 있으니 ConstraintLayout으로 바꾸시는걸 추천드립니다~

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/res/values/colors.xml
> +	<!-- custom -->
custom을 지우고 그냥 palette 아래로 쭉 필요한 color들 적어가는 방식으로 가는건 어떨까요?

아래처럼

```
<color name="_171717">#171717</color>
<color name="_CDCDCD">#CDCDCD</color>
```

나머지 color들은 제가 한번에 정리하겠습니다.

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/res/values/dimens.xml
> +    <dimen name="login_button_icon_size">37dp</dimen>
저도 처음엔 dimen으로 설정해서 하는 방식을 몇번 써봤는데, 프로젝트가 커질수록 관리가 더 힘들더라구요. 그냥 37dp 바로 적는 방식은 어떠신가요?

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/res/values/strings.xml
> +	<!-- login -->
요렇게 카테고리 다신거 좋네요!

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/res/values/themes.xml
> +	<style name="LoginTheme" parent="Theme.AppCompat.Light.NoActionBar">
요 테마는 없어도 됩니다~

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/res/layout/activity_login.xml
> +		android:fitsSystemWindows="true">
요거 없어도 될거에요~

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/res/layout/activity_login.xml
> +				android:lineSpacingExtra="3dp"
여기도 제플린엔 5sp로 되어 있는데 확인 한번 부탁드립니다.

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/java/org/positive/daymotion/presentation/login/LoginActivity.kt
> +        val kakaoStr = "kakaoTalk"
카카오톡만 소문자로 시작하는데, 의도한건지 디자이너분께 확인 받아보면 좋을것 같아요 (kakaTalk?)

2021-06-13 16:31 UTC, sabgilhun commented on app/src/main/res/layout/activity_login.xml
> +				android:paddingEnd="15dp"
버튼들이 Google은 15dp이고 나머지 전부 16dp End 마진이거든요?, 의도적으로 1dp 차이를 둔건지 디자이너분들께 확인 받아보는게 좋을거 같아요. (일단 여기는 16dp로 바꾸는게 맞아보이네요 제플린 기준상)

2021-06-15 08:38 UTC, mini1385 commented on app/src/main/java/org/positive/daymotion/presentation/base/BaseActivity.kt
> +    protected val binding: B by lazy { DataBindingUtil.setContentView<B>(this, layoutId) }
없으면 빨간줄은 생기는데 괜찮겠죠??

2021-06-15 08:38 UTC, mini1385 commented on app/src/main/java/org/positive/daymotion/presentation/login/LoginActivity.kt
> +        window.statusBarColor = ContextCompat.getColor(applicationContext!!, R.color.colorWhite)
저도 잘 나올줄 알았는데 그대로 실행하면 반투명으로 약간 까맣게 나오더라구요ㅠ AVD로 해서 그런걸까요?

2021-06-15 08:41 UTC, mini1385 commented on app/src/main/res/layout/activity_login.xml
> +			<Button
저도 이렇게 했다가 고쳤는데 요게 나을까요?

2021-06-15 08:42 UTC, mini1385 commented on app/src/main/res/layout/activity_login.xml
> +			<TextView
ConstraintLayout을 안 써봐서 익숙한 걸 쓰게되네요 ㅎㅎ 가운데정렬이 어렵네요

2021-06-15 08:43 UTC, mini1385 commented on app/src/main/res/values/colors.xml
> +	<!-- custom -->
오우 네이밍 굿입니다

2021-06-15 08:43 UTC, mini1385 commented on app/src/main/res/values/strings.xml
> +	<!-- login -->
우와 단비같은 칭찬! 감사합니다 ㅎㅎ

2021-06-15 08:44 UTC, mini1385 commented on app/src/main/res/layout/activity_login.xml
> +				android:paddingEnd="15dp"
오 그러네요 google만 보고 통일시켜버렸어요 16이 맞을거 같아요!

2021-06-15 08:50 UTC, mini1385 commented on app/src/main/res/layout/activity_login.xml
> +			tools:ignore="MissingConstraints">
맨마지막줄꺼는 다 지웠는데 다른거는 지우면 위치가 바뀌어요ㅠ

2021-06-15 17:15 UTC, sabgilhun commented on app/src/main/java/org/positive/daymotion/presentation/base/BaseActivity.kt
> +    protected val binding: B by lazy { DataBindingUtil.setContentView<B>(this, layoutId) }
네 없어도 되야 맞긴해요 ㅜ (아예 컴파일이 안된다면 추가하세요)

2021-06-15 17:16 UTC, sabgilhun commented on app/src/main/res/layout/activity_login.xml
> +			<Button
아아 이럴땐 layout에 onClick을 붙이면 됩니다. 유지시키셔도 돼요~

2021-06-15 18:02 UTC, sabgilhun commented on app/src/main/res/layout/activity_login.xml
> +			tools:ignore="MissingConstraints">
이게 ConstraintLayout 쓸때 제약이 가로, 세로 1개 이상 없을때 에러로 잡아주는걸 무시하는 코드거든요.

맨위 LinearLayout은 제약이 4방향 모두 있기 때문에 없어도 됩니다.

```
app:layout_constraintEnd_toEndOf="parent" // end
app:layout_constraintStart_toStartOf="parent" // start
app:layout_constraintTop_toTopOf="parent" // top
app:layout_constraintBottom_toTopOf="@id/personalInformation" // bottom
```
그리고 그 아래 TextView들은 부모 Layout이 LinearLayout이기 때문에 필요 없어요~ (위에서 말했듯이 ConstraintLayout을 위한 속성입니다.)

그리고 참고로 tools로 시작되는 애들은 실제 코드에는 반영되지 않아요. 오른쪽 preview에만 적용되는 코드입니다.

2021-06-15 18:02 UTC, sabgilhun commented on app/src/main/res/layout/activity_login.xml
> +			<TextView
익숙하지 않으시면 두셔도 돼요. 제가 나중에 수정하겠습니다~

2021-06-16 03:36 UTC, sabgilhun approved these changes
LGTM

2021-06-16 03:38 UTC, merged