Mini1385/setting edit
4sitive/client pull request #39
Opened 2021-06-23 14:38 UTC by mini1385

## 작업 내용 
- login 일부 수정
- setting 화면 제작
- dialog 수정

resolve: #38

2021-06-23 15:36 UTC, sabgilhun requested changes
거의 완벽하네요 👍  (리뷰단거는 제가 작업한 부분들도 있어서 지은님 작업은 거의 완벽입니다)

2021-06-23 15:36 UTC, sabgilhun commented on app/src/main/java/org/positive/daymotion/presentation/login/LoginActivity.kt
> -                override fun updateDrawState(ds: TextPaint) {
@mini1385 요거

```
override fun updateDrawState(ds: TextPaint) {
}
```

이렇게 내부 내용 없이 비워 둬야 언더라인 없어져요!

기본 동작이 언더라인 추가해주기 때문에 강제로 없애려면 아무것도 안하도록 변경해야 합니다.

2021-06-23 15:36 UTC, sabgilhun commented on app/src/main/java/org/positive/daymotion/presentation/setting/SettingTabFragment.kt
> +            showPopupDialog {
@mini1385 아까 배경 라운딩 안먹던거 아래처럼 하면 고쳐지네요.

theme.xml 에 아래 코드 추가
```
<style name="CommonDialogTheme" parent="Theme.AppCompat.Light.Dialog.Alert">
    <item name="android:windowBackground">@drawable/background_dialog</item>
</style>
```

DialogDls.kt에 `fun build`에서 

```
        val dialog = AlertDialog.Builder(context)
            .setView(binding.root)
            .create()
```

를

```
        val dialog = AlertDialog.Builder(context, R.style.CommonDialogTheme)
            .setView(binding.root)
            .create()
```

로 변경

2021-06-23 15:36 UTC, sabgilhun commented on app/src/main/java/org/positive/daymotion/presentation/setting/SettingTabFragment.kt
> +                title = "탈퇴하시려구요?"
@mini1385 추가로 지금 다이얼로그 폭이 화면 폭 좀 넓은대, 

아까 추가했던 style에 

`<item name="android:windowMinWidthMinor">83%</item>` 이 항목 추가해주세요

스크린에서 가로, 높이 중 작은 값(보통은 가로겠죠)에 83%정도 크기로 다이얼로그가 뜨도록 하는 코드입니다.
(제플린 시안보면 화면이 360dp 다이얼로그가 300dp 니까 83.33333...% 이더라구요)

2021-06-23 15:36 UTC, sabgilhun commented on app/src/main/res/layout/widget_common_dialog.xml
> +        android:background="@drawable/background_dialog"
@mini1385 아까 위에서 라운드 넣는거 추가 했기 때문에 여기 백그라운 설정은 지워도 될거에요~

2021-06-24 08:36 UTC, mini1385 commented on app/src/main/java/org/positive/daymotion/presentation/login/LoginActivity.kt
> -                override fun updateDrawState(ds: TextPaint) {
맞다.. 알려주셨었는데.. 다시 추가하겠습니다ㅜㅜ

2021-06-24 10:00 UTC, mini1385 commented
완벽이라니.. 감동.. 아직 한참 멀었지만ㅎㅎㅎ 꼼꼼히 알려주셔서 감사해요!

2021-06-24 10:49 UTC, sabgilhun commented on app/src/main/java/org/positive/daymotion/presentation/setting/SettingTabFragment.kt
> +            showPopupDialog {
수정된거 봤는데 theme 넣어주는곳 빠진거 같은데 라운딩이랑 폭 변경되었나요?

2021-06-24 11:05 UTC, mini1385 commented on app/src/main/java/org/positive/daymotion/presentation/setting/SettingTabFragment.kt
> +            showPopupDialog {
신기하게 폭은 변경되었었네용.. 다시 수정했습니다!!

2021-06-24 11:21 UTC, sabgilhun approved these changes
굿굿

2021-06-24 11:21 UTC, sabgilhun commented on app/src/main/java/org/positive/daymotion/common/DialogDsl.kt
> +    var blueButtonText: String = "확인"
실천력 최고 👍  ㅋㅋㅋ

2021-06-24 11:21 UTC, merged